### ISSUE TITLE
Find one-gadgets in normal binaries

### ISSUE THREAD

**Issue by icemonster** [david942j/one_gadget#111]
Is it possible to use one_gadget on a normal binary? Sometimes in CTFs there are calls to execve("/bin/sh") somewhere in user code.

One hackish way I found to make one_gadget work on a normal binary is by converting it to a shared object with `ld -r binary` but that does not work with non-PIE binaries, among other possible problems :)

**Comment by david942j** [comment]
Thanks for your suggestion!

Sadly one_gadget cannot find gadgets in non-glibc binaries, at least for now.
The efficiency and correctness of one_gadget comes from rule-based instruction matching, and the rules can only apply on glibc libraries.

To support normal binaries, a robust methods is needed (and a lot changes are expected) to do the emulation on assembly (e.g. using [unicorn](https://github.com/unicorn-engine/unicorn/)), and the emulator has to support symbolic execution to find the conditions that make one_gadget(s) succeed.
Marking this issue as a feature request and patches are welcome, I may also work on this when I have time. To start, could you provide the binary(ies) you got in the CTFs? They can be good examples and useful for testing.

In the other hand, it might be good to have one_gadget be able to find one-gadgets in a stripped statically-linked binary, but that's another story.

**Comment by XaiDang99** [comment]
What should u do@Inndy 🤔

**Comment by XaiDang99** [comment]
Need help ![1680658522392.png](https://user-images.githubusercontent.com/105825550/229963997-0a1ba4b6-5648-459d-afaa-1cb3bce23ef5.png)
