### ISSUE TITLE
No gadgets found for BuildID[sha1]=f46739d962ec152b56d2bdb7dadaf8e576dbf6eb

### ISSUE THREAD

**Issue by johnchen902** [david942j/one_gadget#14]
Apparently this tool find no gadgets on my machine: (wrapped mine)

```
$ file /lib/libc-2.26.so 
/lib/libc-2.26.so: ELF 64-bit LSB shared object, x86-64, version 1 (GNU/Linux),
dynamically linked, interpreter /usr/lib/ld-linux-x86-64.so.2,
BuildID[sha1]=f46739d962ec152b56d2bdb7dadaf8e576dbf6eb, for GNU/Linux 3.2.0, not stripped
$ ~/.gem/ruby/2.4.0/bin/one_gadget --version
OneGadget Version 1.4.0
$ ~/.gem/ruby/2.4.0/bin/one_gadget /lib/libc-2.26.so 

$ 
```
[libc-2.26.so.zip](https://github.com/david942j/one_gadget/files/1431403/libc-2.26.so.zip)

This build is distributed by Arch Linux glibc 2.26-5. Until next update, you can also download a copy from any Arch Linux mirror.

I don't know if it's a bug or glibc has hardened itself though.

**Comment by david942j** [comment]
I guess this is duplicated with #12 , which is fixed in master branch
I'll draft version 1.4.1 and the issue should be solved.

**Comment by david942j** [comment]
version 1.4.1 released
