### ISSUE TITLE
Some gadgets are missing

### ISSUE THREAD

**Issue by umutoztunc** [david942j/one_gadget#153]
For the libc file with the hash `4fcd76645607f38d91f65654ddd6b9770b5ea54a`, there are only 3 gadgets found even with the --level parameter:
![image](https://user-images.githubusercontent.com/32958854/104164424-f281da80-5408-11eb-8af0-632b413fc19a.png)

However, there are more gadgets at location 0xE6C7E:
![image](https://user-images.githubusercontent.com/32958854/104164650-468cbf00-5409-11eb-9214-06a6578154c4.png)

**Comment by david942j** [comment]
Duplicate to #119, sorry I didn't create a new release with the fix (#122)

**Comment by david942j** [comment]
This will be fixed in 1.7.4 (the next release)
