### ISSUE TITLE
misleading install instructions

### ISSUE THREAD

**Issue by k4lizen** [david942j/one_gadget#215]
the readme says:
`$ gem install one_gadget`
this fails for me with permissions errors.
`gem install one_gadget --user-install`
works for me after adding `one_gadget` to path.

**Comment by david942j** [comment]
Usually I recommend using local env tools for Ruby management such as `rvm` or `rbenv`, with which you can do `gem install` without passing `sudo` (neither `--user-install`).

This is a common package management design issue even for Python (pip), it's not a misleading instruction specific to `one_gadget` :)

Ref: https://stackoverflow.com/questions/2119064/sudo-gem-install-or-gem-install-and-gem-locations

**Comment by k4lizen** [comment]
> This is a common package management design issue even for Python (pip)

Except `pip install <program>` would actually work... But okay, thanks for the Ref.
