### ISSUE TITLE
Consider xmm* registers in symbolic execution

### ISSUE THREAD

**Issue by david942j** [david942j/one_gadget#26]
in libc-2.27.so on ubuntu 18.04:
```asm
   4f2ec:       48 89 44 24 08          mov    QWORD PTR [rsp+0x8],rax
   4f2f1:       0f 16 44 24 08          movhps xmm0,QWORD PTR [rsp+0x8]
   4f2f6:       0f 29 44 24 40          movaps XMMWORD PTR [rsp+0x40],xmm0
```
This should be considered as equivalent to `mov [rsp+0x48], rax`

**Comment by david942j** [comment]
And need to add a constraint: `rsp & 0xf == 0`

**Comment by gsingh93** [comment]
> And need to add a constraint: rsp & 0xf == 0

@david942j: Is this supposed to show up in the output? I'm using `one_gadget` on Ubuntu 18.04 with libc-2.27.so, and it's not telling me the stack needs to be aligned to 16 bytes for XMM instructions.

**Comment by david942j** [comment]
No, it's not implemented yet

**Comment by gsingh93** [comment]
Ok, I'll create an issue since this one is closed.
