### ISSUE TITLE
Annoying update check

### ISSUE THREAD

**Issue by matrix1001** [david942j/one_gadget#42]
Some time I got update check information in `one_gadget -r` , pretty annoying when I use python to get those offsets automatically.

I think `-r` option should not contain update info. Any way to avoid this exclude changing my script?

**Comment by david942j** [comment]
Is this helpful?
```
To disable this functionality, do
$ echo never > $HOME/.cache/one_gadget/update
```

**Comment by david942j** [comment]
How about no update checking if stdout is not tty?
In this way the check will not be triggered if you use something like `subprocess.check_output`, but will be triggered via CLI.

**Comment by david942j** [comment]
A new version 1.6.1 with the fix has drafted as well
