### ISSUE TITLE
Use LibcDB BuildID Database

### ISSUE THREAD

**Issue by zachriggle** [david942j/one_gadget#5]
I am the maintainer of LibcDB (https://gitlab.com/libcdb/libcdb) which is a database of all of the libc for various distributions.

You can perform a lookup of a given libc via BuildID, SHA1, MD5, or SHA256.

https://gitlab.com/libcdb/libcdb/tree/master/hashes

Here's an example of one of the existing builds, below.  If you clone the repo (warning: 30+GB) it'll be a symlink to the actual file.

https://gitlab.com/libcdb/libcdb/blob/master/hashes/build_id/369de0e1d833caa693af17f17c83ba937f0a4dad

To download the actual file directly, you can use the following link (i.e., replace `blob` with `raw` in the URL)

https://gitlab.com/libcdb/libcdb/raw/master/hashes/build_id/369de0e1d833caa693af17f17c83ba937f0a4dad

It may be useful to integrate your tool with this functionality, since LibcDB is updated daily (though there are not always new libc to actually update, it just runs as a cron job):

https://gitlab.com/libcdb/libcdb/activity

**Comment by david942j** [comment]
Thanks your recommendation!
I'll take a look.

**Comment by david942j** [comment]
BTW, I found this link throws an internal server error: https://gitlab.com/libcdb/libcdb/tree/master/hashes/build_id

**Comment by zachriggle** [comment]
Yes, there are tens of thousands of hashes, their website won't let you
browse them. Clone the repo to browse.

**Comment by david942j** [comment]
https://github.com/david942j/one_gadget/pull/6
