### ISSUE TITLE
Other architectures support

### ISSUE THREAD

**Issue by david942j** [david942j/one_gadget#62]
Currently `one_gadget` is based on objdump's output, so the biggest issue is how to make users to have the specific version of objdump.

I have two ways to resolve this issue:
1. Ask users clone the official binutils repo and compile an all-architectures-supported objdump.
    - pros: the objdump supports many architectures
    - cons: need more user-interactive actions
2. Ask users install the specific objdump from pkg managers.
    - pros: installing things from trusted pkg managers is more comfortable to users
    - cons: will need different versions of objdump to support different architectures.

Need discussions @scwuaptx

**Comment by david942j** [comment]
Edit: just found there're `binutils-multiarch` available on apt, so maybe this is a good choice

**Comment by zjgcjy** [comment]
So, how can i  install `binutils-multiarch` in other linux, such as Archlinux. I failed finding the right solution after updating to 1.7. `> <`

**Comment by david942j** [comment]
@zjgcjy sorry I'm not familiar with Archlinux.  If you still fail to find the package of binutils that support multi-architecture, you can compile and install binutils from source.
