### ISSUE TITLE
Add offset feature .

### ISSUE THREAD

**Issue by now4yreal** [david942j/one_gadget#94]
when i use this tool , i'm bothered about having to add an offset to each gadget . Could you please add this feature to this tool ? Thanks a lot !

**Comment by david942j** [comment]
Do you mean you'd like it to accept a 'base' address parameter and add it to the output offsets?
Something like
```
$ one_gadget libc.so
0x12345 ...
...
$ one_gadget libc.so --base 0x7f0000000000
0x7f0000012345 ...
...
```

**Comment by now4yreal** [comment]
Yes . Thanks.
